### ISSUE TITLE
Error Reports

### ISSUE THREAD

**Issue by renschmid** [FrankBijnen/ExifToolGui#269]
@FrankBijnen Here is the error message I received when trying to add Geolocation data from the OSM Map to a 3.8 GB mp4 video file. This is an unusually large file that resulted after I forgot to turn off the camera.

> If understand correctly there are 2 problems,
> •	A large file that won't update. I really would like to see the error message for that one.

First, the settings I used to update the file:

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/23e404f0-2a53-4439-9621-fa3b7beff225)

This is the error dialogue box:

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/a1869d96-90e6-4e98-80de-5c6277a1a287)

In case you cannot view these images, I also include the following:  

> -echo4
> {ready38}
> -CHARSET
> FILENAME=UTF8
> -CHARSET
> UTF8
> -v0
> -overwrite_original
> -sep
> *
> -m
> -c
> %.6f°
> -API
> WindowsWideFile=1
> 
> -a
> -Gps*=
> --GPSversion*
> -GPS:GpsLatitudeRef=N
> -GPS:GpsLatitude=32.7819
> -GPS:GpsLongitudeRef=W
> -GPS:GpsLongitude=79.929353
> -QuickTime:GPSCoordinates='32.7819, 79.92935, 0'
> -xmp:LocationShownCountryName=United States
> -xmp:LocationShownProvinceState=South Carolina
> -xmp:LocationShownCity=Charleston
> -xmp:LocationShownSublocation=
> 2023-11-06_154405.mp4
> -execute38

AND

> Error: End of processing at large atom (LargeFileSupport not enabled) - 2023-11-06_154405.mp4

I hope this information assists you.

Rennie

**Comment by FrankBijnen** [comment]
Hi Rennie,

This sure helps.
You file is bigger than 2 GigaByte, and that needs a special ExifTool option. '-API LargeFileSupport=1'.

in ExifToolGui click on Options/Custom options:

![options](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/421c3756-4e6e-4ed3-b486-a547eb12320b)

Paste -API LargeFileSupport=1 in the Edit box and Click OK.

![LargeFile](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/18ab5a21-39f8-4c90-9b62-3c62f797b0f0)

With every ExifTool call this option will now be passed. You can check that in the Log Window.

That should do it.

Frank

More info:
https://exiftool.org/forum/index.php?topic=9845.0
https://exiftool.org/ExifTool.html#LargeFileSupport

**Comment by renschmid** [comment]
Thanks, I will test it. Give me a couple of minutes and I will be send a more detailed report about the server-based errors on modifying files. I think I found a pattern.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by renschmid** [comment]
@FrankBijnen Here is the information relating to Modifying a group of selected files that have imbedded GPSCoordinates. I will list the results from using both servers.

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/76a3cc47-2a7a-4790-989a-bc04dec7e2c2)

Error:

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/b525b879-85b6-4133-81c8-3214cff36ffd)

**_Note: This message occurs on processing the last file (10th File) in the selection. So I think it may relate to the end of the loop._**

Now for the alternative server:

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/6cfbd433-38e1-422c-9a19-b4873a9234d8)

Error:

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/a6b20573-aaf3-46c3-923a-13389bb7f636)

**_Note: This error occurred on the 5th file (There were 10 files). It continued to complete the task. No more errrs._**

**Important Note: I discovered that the folder contained a jpg file. This test omitted this jpg file. I didn't realise the file was mixed in with the video files.**

**Conclusion:** While I received different error messages from each server, I noticed that Geocode errored after the 5th file on the first test, but did not error when tested a second time. I kept repeating the test on the same selection and the error continued after the 5th file and they all finished after I clicked "Yes" on the error message.

  Overpass errored on the last file. Second run it did not error, while on the third run it errored on the last file.

**Comment by FrankBijnen** [comment]
Just notices an unwanted sideeffect of the -API LargeFileSupport=1.
The next time you start ExifToolGui the MetaDatalist is 'garbled'. Please remove the option after the test!

![largefile](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/d808061f-d4da-4b51-8fda-0a4f5c619d75)

I will fix this for the next release.

**Comment by FrankBijnen** [comment]
Hi Rennie.

Now for the other errors. I read a few things.

- Mixing JPG and Movie files. Do you think that has anything to do with it? Cant imagine.
- Some requests fail on a file, but when you repeat it that same file gives no error. Could be a 'Server overload'. Could you please check the settings. And 'play' with throttle values. Increase them to 5000 for example and see if that works.

The GEoCode requests are also logged in the log-window, I would like that info. So:
- Open the log window
- Execute the function.
- Look in the Log Window for the 'REST REQUEST' that has an error. And send that please.

Frank
![prefs](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/93c52011-6806-40e6-a109-ad409e5f7cea)
![restlog](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/ec8b8cf6-749d-440a-9d70-00b54c2d81ae)

**Comment by renschmid** [comment]
Hi Frank,

I increased the Throttle values to 1000 (GeoCoding) and 20 (Overpass) and eliminated the errors. I will keep checking, as there are a lot of videos to update. If it reappears, I will send you any log details.

Regards

Rennie

**Comment by renschmid** [comment]
Hello again, Frank,

The large file fix did not work on my system. I get the same error message. I will go back to the original file to test if the file somehow corrupted when I copied from another driver. I don't think this is the issue and I can play to file.

**Comment by FrankBijnen** [comment]
Hello Rennie.

"I increased the Throttle values to 1000 (GeoCoding) and 20 (Overpass) and eliminated the errors. I will keep checking, as there are a lot of videos to update. If it reappears, I will send you any log details."

If I understand correctly you have made some progress with the Throttle values. Good!

"The large file fix did not work on my system. I get the same error message. I will go back to the original file to test if the file somehow corrupted when I copied from another driver. I don't think this is the issue and I can play to file."

There was a bug (Yes. ExifToolGui has bugs!) that did not save the 'Custom Options' correctly. So next time you started GUI the parameter was not effective, and even caused the Metadata to display incorrect. I have corrected that bug and uploaded the version to Onedrive. https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Please download that version, and try again with the Custom Option set to '-API LargeFileSupport=1' (Without the quotes) and the Low Window open.

Meanwhile I'm convinced that when sending Images, attachments etc, you should not reply to the mail. Because that will drop the attachments. Instead add them to the issue here.

Turns out this is a 'hard nut to crack', but I'm not giving up yet. Hope you arent either. And the time difference doesn't help. The last mail I read from you yesterday it was 01.00 AM here (after midnight)

Thanks for your cooperation,
Frank

**Comment by renschmid** [comment]
Yes, adjusting the throttle values worked. That was pleasing.

I am happy to help you crack the nut!! I have to work tomorrow, but will try and keep up with you. Where are you located?

I have downloaded the latest version and followed your directions. Unfortunately, the problem remains. Here is the error message:

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/4210fb69-9462-4507-9580-038174e7838b)

> -echo4
> {ready33}
> -CHARSET
> FILENAME=UTF8
> -CHARSET
> UTF8
> -v0
> -overwrite_original
> -sep
> *
> -m
> -c
> %.6f°
> -API
> WindowsWideFile=1
> 
> 
> -xmp:LocationShownCountryName=United States
> -xmp:LocationShownProvinceState=South Carolina
> -xmp:LocationShownCity=Charleston
> -xmp:LocationShownSublocation=Carriage Ride
> 2023-11-06_154405.mp4
> -execute33
> 
>

**Comment by FrankBijnen** [comment]
I live in the Netherlands (UTC +1) 

I can see from the Log that the '-API LargeFileSupport=1' is missing. This is how it should look.
![largelog](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/b15e5044-1ff3-4460-b153-213282f3c3ff)

And you should add it like this
![customoptions](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/cbfed2fa-87d3-4764-a90e-47e4d4db8016)
![customlarge](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/3a4eb8df-43e5-4195-82ee-c6c298d01e1e)

**Comment by FrankBijnen** [comment]
Just out of curiousity, and maybe it helps others having the same problem.
What were your throttle values that gave the error? 

I guess 500 for Geocode and 10 for Overpass.

Initially GeoCode allowed 2 requests per seconds hence the default in GUI was 500, I have changed the default to 1000, but the default is only used the very first time.
For Overpass the default is still 10

**Comment by renschmid** [comment]
This time success! However, the first time is failed. It takes a long time and the computer feels like it frozen. I entered the command again, and this time it worked, but it was very slow. Users will think something is wrong.

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/51b858d5-49af-4cf2-ba31-c0fb3ca1167c)

-echo4
{ready45}
-CHARSET
FILENAME=UTF8
-CHARSET
UTF8
-v0
-overwrite_original
-sep
*
-m
-c
%.6f°
-API
WindowsWideFile=1
-API
LargeFileSupport=1
-g1
-a
-S
-Exif:All
2023-11-06_154405.mp4
-execute45

**Comment by renschmid** [comment]
> What were your throttle values that gave the error?

They were the defaults. So it was only a small increase.

Would internet latency cause the problem? I notice that my latency has been hight this week. Ping is excellent, but download latency is too high.

**Comment by FrankBijnen** [comment]
"They were the defaults. So it was only a small increase. "
Yes, but if that's 500 ms delay it's to small, You could theoritically have 2 requests per secs. So that's to much if you're only allowed 1 call per seconds.

"Would internet latency cause the problem? I notice that my latency has been hight this week. Ping is excellent, but download latency is too high."
It would only help because you wouldn't be able to execute that many request per sec.

**Comment by FrankBijnen** [comment]
I think we can close the issue for now. What do you think? 

I will add LargeFileSupprt as an option, and write something in the docs with the things we learned.

P.S. The next few days we're off to see our doughter who live 100 miles up north. So I might not respond, but I'll get back to you.

**Comment by renschmid** [comment]
Yes, I think this is a good start. Just comment that large files may take a long time.

We are going away on the weekend to see my wife's mother. I can still work on it as we will have internet. Enjoy your visit.

**Comment by FrankBijnen** [comment]
"Note: execute 52 followed 2 second later, but there was no "OK""

If you have checked 'Show all commands' it will also show the commands needed to show the info on the screen. These are not checked for success. 

Enjoy yours too. And thanks for the help. Really appreciate it.
Frank

**Comment by FrankBijnen** [comment]
Hi Rennie,

Just released a new version of ExifToolGui, It incorporates the changes we identified.
https://github.com/FrankBijnen/ExifToolGui/releases/tag/V6.2.9

This is the updated documentation of the GeoCoding.
https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/Readme%20GeoCoding.txt

Thanks
Frank

**Comment by renschmid** [comment]
Thanks, Frank,

I appreciate the work you have put into this. If I can help testing it please let me know.

Rennie.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
